name: Check pipeline

on:
  push:
    branches: [ ci_cd ]
  pull_request:
    branches: [ dev, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install ruff
        run: pip install ruff

      - name: Lint check
        run: ruff check .

      - name: Format check
        run: ruff format --check .


  test:
    name: Run api tests
    needs: [ lint ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start services
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_AUTH: ${{ vars.POSTGRES_DB_AUTH }}
          POSTGRES_DB_UNIVERSITY: ${{ vars.POSTGRES_DB_UNIVERSITY }}
          AUTH_SERVICE_INTERNAL_URL: ${{ vars.AUTH_SERVICE_INTERNAL_URL }}
          UNIVERSITY_SERVICE_INTERNAL_URL: ${{ vars.UNIVERSITY_SERVICE_INTERNAL_URL }}
        run: docker compose up -d

      - name: Build tests container
        run: docker build -t api-tests -f Dockerfile .

      - name: Run API tests with Allure
        run: |
          docker run --rm --network=api-tests-network \
            -e AUTH_SERVICE_API_URL='http://auth:8000' \
            -e UNIVERSITY_SERVICE_API_URL='http://university:8000' \
            -v $(pwd)/allure-results:/app/allure-results \
            api-tests python -m pytest -v \
            --tb=short \
            --alluredir=allure-results

      - name: Store Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 3

      - name: Cleanup
        if: always()
        run: docker compose down -v

  allure-report:
    name: Allure report
    needs: [ test ]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate and Deploy Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          subfolder: latest
          keep_history: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './allure-report'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
