name: Check pipeline

on:
  push:
    branches: [ ci_cd ]
  pull_request:
    branches: [ dev, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install ruff
        run: pip install ruff

      - name: Lint check
        run: ruff check .

      - name: Format check
        run: ruff format --check .


  setup-services:
    name: Setup test services
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start services
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_AUTH: ${{ vars.POSTGRES_DB_AUTH }}
          POSTGRES_DB_UNIVERSITY: ${{ vars.POSTGRES_DB_UNIVERSITY }}
          AUTH_SERVICE_INTERNAL_URL: ${{ vars.AUTH_SERVICE_INTERNAL_URL }}
          UNIVERSITY_SERVICE_INTERNAL_URL: ${{ vars.UNIVERSITY_SERVICE_INTERNAL_URL }}
        run: docker compose up -d

  test:
    name: Run api tests
    needs: [ setup-services ]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build tests container
        run: docker build -t api-tests -f Dockerfile .

      - name: Run API tests inside Docker container
        run: |
          docker run --rm --network=api-tests-network \
            api-tests pytest -v

