name: Check pipeline

on:
  push:
    branches: [ ci_cd ]
  pull_request:
    branches: [ dev, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install ruff
        run: pip install ruff

      - name: Lint check
        run: ruff check .

      - name: Format check
        run: ruff format --check .


  setup-services:
    name: Setup test services
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start services
        run: docker compose up -d

#  test:
#    name: Run API tests
#    needs: [ setup-services ]
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Build tests container
#        run: docker build -t api-tests -f Dockerfile.tests .
#
#      - name: Run API tests inside Docker container
#        run: |
#          docker run --rm --network=api-tests-network \
#          -v $(pwd)/allure-results:/app/allure-results \
#          -e AUTH_SERVICE_API_URL='http://auth:8000' \
#          -e UNIVERSITY_SERVICE_API_URL='http://university:8000' \
#          api-tests pytest
#
#      - name: Store Allure results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results
#          path: allure-results
#          retention-days: 1